apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      name: backend-api
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: roelvandegrint.azurecr.io/backend-api:902e9f20b3254e303fa68c469f58f8b7e4eb7d16
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        env:
        - name: LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE
          value: Information
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
