apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      name: public-api
      labels:
        app: public-api
    spec:
      containers:
      - name: public-api
        image: roelvandegrint.azurecr.io/public-api:b434e4f111ef70ac7b95c6a1f1bd8289663ae1e7
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        env:
        - name: LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE
          value: Information
        - name: BACKENDAPIBASEADDRESS
          value: http://backend-api
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
