apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      name: public-api
      labels:
        app: public-api
    spec:
      containers:
      - name: public-api
        image: roelvandegrint.azurecr.io/public-api:042e070e2fffa0c72f66c88b5a07480892f6ccbd
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: public-api-configmap
        - secretRef:
            name: public-api-database
        - secretRef:
            name: public-api-servicebus
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
