apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api

spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      name: public-api
      labels:
        app: public-api
    spec:
      containers:
      - name: public-api
        image: roelvandegrint.azurecr.io/public-api:ea544599409fc8c3e4f9669dbb7854256e9581d6
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: public-api-configmap
        - secretRef:
            name: public-api-secrets
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
