@domain = localhost
@port = 5094

GET http://{{domain}}:{{port}}/employees HTTP/1.1

###
GET http://{{domain}}:{{{{port}}/employees/1 HTTP/1.1

###
POST http://{{domain}}:{{port}}/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Roel",
    "prefix": "van de",
    "lastName": "Grint"
}

###
DELETE http://{{domain}}:{{port}}/employees/611d5d5b-4baa-4581-b391-08dab8fac6a8 HTTP/1.1