GET http://127.0.0.1:5000/employees HTTP/1.1

###
GET http://127.0.0.1:5000/employees/1 HTTP/1.1

###
POST http://127.0.0.1:5000/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Roel",
    "prefix": "van de",
    "lastName": "Grint"
}