name: Backend API Build 

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - main
    paths:
      - backend.API/**

  # Allow mannually trigger
  workflow_dispatch:

env:
  REGISTRY: roelvandegrint.azurecr.io
  IMAGE_NAME: backend-api
  DIRECTORY: backend.API
  DOCKERFILE: backend.API/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      #Build and push Docker image with Buildx (don't push on PR)
      #https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          file: ${{ env.DOCKERFILE }}
          context: ${{ env.DIRECTORY }}
          platforms: linux/amd64,linux/arm64
          push: true

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: kubernetes/backend-api.deployment.yml
          find: "image:\\s*.*\n"
          replace: "image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          regex: true

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

# .github/workflows/backend-api-build-and-push.yml
# image: roelvandegrint.azurecr.io/backend-api:8951af42b90f3e79f5db4b6ccb177ae122917059