name: trigger test

# When this action will be executed
on:
  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout to the branch
        uses: actions/checkout@v2
      
      - name: Trigger new Operation-Resource actions for Deployment
        run: |
          curl -X POST https://api.github.com/repos/roelvandegrint/microservices-gitops-infrastructure/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u "${{ secrets.PAT }}"
          --data '{"event_type": "product", "client_payload": { "what": "coolness" }}'
